### ISSUE TITLE
It is trying to login, but redirecting me.

### ISSUE THREAD

**Issue by eleijonmarck** [cvhau/pinterest-client#1]
Hey man!

I am trying to login to my account, however it gets stuck when I am loggin in with redirecting me. I have tried to set the upper limit higher but without success. Have you experienced this and how did you avoid it?

```
class Pinterest:
    home_page = 'https://www.pinterest.com/'

    def __init__(self, username_or_email, password, proxies=None, agent_string=None):
        self.debug = False
        self.is_logged_in = False
        self.user = None
        self.http = requests.session()
        self.http.max_redirects = 100
        self.username_or_email = username_or_email
```

Traceback call
```
Traceback (most recent call last):
  File "fireinterest.py", line 18, in <module>
    logged_in = pinterest.login()
  File "/Users/ericleijonmarck/dev/firesocial/pinterestPy/pinterest-client/pinterest/Pinterest.py", line 110, in login
    r = self.get(self.home_page)
  File "/Users/ericleijonmarck/dev/firesocial/pinterestPy/pinterest-client/pinterest/Pinterest.py", line 80, in get
    return self.request('GET', url=url, params=params, headers=headers, ajax=ajax, stream=stream)
  File "/Users/ericleijonmarck/dev/firesocial/pinterestPy/pinterest-client/pinterest/Pinterest.py", line 71, in request
    files=files, timeout=60, proxies=self.proxies, stream=stream)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 100 redirects.
```

**Comment by ymongo** [comment]
same here, haven't tried with 100 redirects though!!!

**Comment by JOOKER69** [comment]
add "allow_redirects=False" in
Pinterest.py Line 69:
so edit from:
> response = self.http.request(method, url, params=params, data=data, headers=_headers,
                                     files=files, timeout=60, proxies=self.proxies, stream=stream)

to:
> response = self.http.request(method, url, params=params, data=data, headers=_headers,
                                     files=files, timeout=60, proxies=self.proxies, stream=stream, allow_redirects=False)

**Comment by Deb23** [comment]
The code update still doesn't work. Was anyone able to resolve the "TooManyRedirects" exception?

**Comment by lasalesi** [comment]
Had the same error

    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)

With the modification from JOOKER69, the new error is 

    requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://www.pinterest.com/resource/UserSessionResource/create/

So there seems to still be an issue here...

**Comment by void285** [comment]
Same error here.

**Comment by void285** [comment]
I fount these errors seem to be related to "geographical redirects".

**Comment by DanBelo** [comment]
any update on this issue, i have the same problem

**Comment by ayush-sriv** [comment]
I solved this issue by downloading the code and then changing all occurrences of 'www.pinterest.com' to 'in.pinterest.com' in the `Pinterest.py` file. I changed it to `www` to `in` because I live in India and every time I go to www.pinterest.com on my browser it redirects me to in.pinterst.com. You should check where does your browser redirect you and change it to that address.
