### ISSUE TITLE
Is it still work?

### ISSUE THREAD

**Issue by canberkozer** [cvhau/pinterest-client#10]
I tried to install but I found this error "Could not find a version that satisfies the requirement pinterest-client (from versions: )
No matching distribution found for pinterest-client"

Is it still working?

**Comment by bstoilov** [comment]
Hello, the pip install is not working.
To use it you can download the project and use setup.py to install it.

It is working only with python 2.7, I am currently rewriting it for python 3, but I can confirm that all of the functionalities are still working as of today.

Kudos to the developer!

**Comment by flygohr** [comment]
Installing it via git clone helped but..now I get this:
```
pinterest.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pinterest/Pinterest.py", line 109, in login
    r = self.get(self.home_page)
  File "pinterest/Pinterest.py", line 79, in get
    return self.request('GET', url=url, params=params, headers=headers, ajax=ajax, stream=stream)
  File "pinterest/Pinterest.py", line 70, in request
    files=files, timeout=60, proxies=self.proxies, stream=stream)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by bstoilov** [comment]
Yes it has a lot of problems when you use it with newer python versions, I ended up rewriting it nearly from scratch.
That particular issue is caused by change in pinterest api.

I don't like promoting my repo on other people's projects but here is it -> https://github.com/bstoilov/py3-pinterest
Basically same thing but I updated some endpoints added new ones and rewrite it for python 3

**Comment by flygohr** [comment]
I see. I am setting it up right now. I am using your example, which I suppose contains all the available functions..any chance you'd be available for a quick help into getting it started?

**Comment by bstoilov** [comment]
There are already several people that are using it and it is working for them. If you have any issue report it there so we don't flood this project
