### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by abdulahad7** [cvhau/pinterest-client#11]
I am working on python 2. An error appearing on login
Traceback (most recent call last):
  File "d:\Python Projects\pinterest-client-master\test01_pinterest.py", line 3, in <module>
    pinterest = Pinterest(username_or_email='user@gmail.com', password='pass')
  File "d:\Python Projects\pinterest-client-master\pinterest\Pinterest.py", line 34, in __init__
    self.registry = Registry('%sregistry.dat' % self.data_path)
  File "d:\Python Projects\pinterest-client-master\pinterest\Registry.py", line 15, in __init__
    self.__data = dict(pickle.load(f))
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "C:\Python27\lib\copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: object.__new__(X): X is not a type object (classobj)

**Comment by bstoilov** [comment]
Hi this is related to a change in the pinterest login endpoint. I had to reintegrated with the pinterest api again in order to make it work.
https://github.com/bstoilov/py3-pinterest
Most of the pinterest endpoint have changes in them, so you will have more issues like this.
