### ISSUE TITLE
TypeError when trying to login

### ISSUE THREAD

**Issue by Latand** [cvhau/pinterest-client#6]
Hey, I'm trying to login, but TypeError is raised.

TypeError: a bytes-like object is required, not 'str'
```
>>> logged_in = pinterest.login()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Documents\GitHub\pinterest-client\pinterest\Pinterest.py", line 110, in login
    self.user = self.extract_user_data(r.content)
  File "C:\Users\User\Documents\GitHub\pinterest-client\pinterest\Pinterest.py", line 93, in extract_user_data
    s = html_page[html_page.rfind('application/json'):]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by bryanmorganoverbey** [comment]
works for me...

**Comment by bryanmorganoverbey** [comment]
from pinterest import Pinterest
pinterest = Pinterest(username_or_email='username', password='pass')

^^make sure you have these lines first

**Comment by qwhex** [comment]
Pyhton2 is needed

**Comment by qwhex** [comment]
You should run it with Python2

**Comment by Latand** [comment]
Too bad.
