### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by DanBelo** [cvhau/pinterest-client#8]
Traceback (most recent call last):
  File "pin.py", line 9, in <module>
    boards = pinterest.boards()
  File "E:\Python27\lib\site-packages\pinterest\Pinterest.py", line 146, in boar
ds
    'source_url': '/%s/pins/' % self.user['username'],
TypeError: 'NoneType' object has no attribute '__getitem__'

e:\PYS>python pin.py
Traceback (most recent call last):
  File "pin.py", line 10, in <module>
    pinterest.create_board(name='Board name', description='Description')
  File "E:\Python27\lib\site-packages\pinterest\Pinterest.py", line 174, in crea
te_board
    'source_url': '/%s/boards/' % self.user['username'],
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by bstoilov** [comment]
Are you using python 2.7?
